# Generated by Django 5.2.1 on 2025-05-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=60)),
                ('stu_photo', models.ImageField(blank=True, null=True, upload_to='book_images/')),
            ],
        ),
    ]
