# Generated by Django 5.2.1 on 2025-05-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=60)),
                ('email_id', models.EmailField(max_length=80)),
                ('stu_photo', models.ImageField(blank=True, null=True, upload_to='stu_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='FormStudent',
        ),
    ]
