# Generated by Django 5.2 on 2025-04-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_author_author1_department_details2_book_book1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book1',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Author1',
        ),
        migrations.DeleteModel(
            name='Book1',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
