# Generated by Django 5.2 on 2025-04-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0004_remove_book_author_remove_book1_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details2',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='details2',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='details2',
            name='phone_no',
            field=models.CharField(max_length=20),
        ),
    ]
