# Generated by Django 5.2 on 2025-04-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0005_alter_details2_location_alter_details2_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('students_no', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
