# Generated by Django 5.2 on 2025-04-28 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0006_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='students_no',
            new_name='student_no',
        ),
    ]
