# Generated by Django 5.2 on 2025-04-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0007_rename_students_no_course_student_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='student_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
