# Generated by Django 5.2 on 2025-04-29 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0009_author_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Authors', 'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Books', 'verbose_name_plural': 'Books'},
        ),
    ]
