# Generated by Django 5.2.1 on 2025-05-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
